### ISSUE TITLE
What is this, there is no README

### ISSUE THREAD

**Issue by vtsatskin** [VicV/syde#1]

**Comment by VicV** [comment]
@vtsatskin will add readme once I get my licenses sorted out. 

There's a few Apache things in here (their headers have the licensing still) but I wanna sort it all out proper before I actually make the readme.

That said:

Its an app that lets you define a region, and collect litter in that region autonomously with the dji phantom.

**Comment by VicV** [comment]
@vtsatskin updated with a small readme for now. Will have a better explanation once we have better demos.
